{% set name = "ibm_db" %}
{% set version = "3.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3c3b4550364a43bf1daa4519b668e6e00e7c3935291f8c444c4ec989417e861
  patches:
    - 0001-Omit-GCC-check.patch

build:
  number: 1
  # the osx-64 libdb2.dylib is built using gcc, which is incompatible with the conda-forge ecosystem
  # otool -L $SP_DIR/clidriver/lib/libdb2.dylib|grep gcc
  # https://github.com/ibmdb/db2drivers/issues/3#issuecomment-2566168370
  skip: true  # [osx and x86_64]
  skip: true  # [win and py==311]
  script: {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}  # [ppc64le]
  host:
    - python
    - pip
    - setuptools
    - libxml2-devel
  run:
    - python
    - setuptools
    - libxcrypt1  # [linux]

test:
  commands:
    - python -c "import os; os.add_dll_directory(os.environ['SP_DIR'] + '\\clidriver\\bin'); import ibm_db; import ibm_db_dbi"  # [win]
  imports:
    - ibm_db  # [not win]
    - ibm_db_dbi  # [not win]

about:
  home: https://pypi.org/project/ibm-db/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Database API Specification v2.0
    The extension supports DB2 (LUW, zOS, i5) and IDS (Informix Dynamic Server)
  doc_url: https://github.com/ibmdb/python-ibmdb/wiki
  dev_url: https://github.com/ibmdb/python-ibmdb

extra:
  recipe-maintainers:
    - SabaKauser
    - xhochy
    - amukherjee28
