{% set name = "ibm_db" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 185de434bf132d16b26e894a213d3f14dc93d75c2f372ef296e79fb904997fb0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - {{ cdt('numactl-devel') }}  # [ppc64le]
  host:
    - python
    - pip
    - setuptools
    - libxml2
  run:
    - python
    - setuptools
    - libxml2

test:
  imports:
    - ibm_db
    - ibm_db_dbi

about:
  home: https://pypi.org/project/ibm-db/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Database API Specification v2.0
    The extension supports DB2 (LUW, zOS, i5) and IDS (Informix Dynamic Server)
  doc_url: https://github.com/ibmdb/python-ibmdb/wiki
  dev_url: https://github.com/ibmdb/python-ibmdb

extra:
  recipe-maintainers:
    - SabaKauser
    - xhochy
    - amukherjee28
