{% set name = "ibm_db" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec7075246849437ed79c60447b05a4bee78a3f6ca2646f4e60a028333c72957a
  patches:
    - 0001-Omit-GCC-check.patch

build:
  number: 1
  # The macOS binary is built using GCC and thus incompatible with libcxx
  # otool -L $SP_DIR/clidriver/lib/libdb2.dylib|grep gcc
  # See also
  # * https://github.com/ibmdb/python-ibmdb/issues/835
  # * https://github.com/ibmdb/python-ibmdb/issues/804
  # * https://github.com/ibmdb/python-ibmdb/issues/824
  skip: true  # [osx]
  skip: true  # [win and py==311]
  script: {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}  # [ppc64le]
  host:
    - python
    - pip
    - setuptools
    - libxml2
  run:
    - python
    - setuptools
    - libxml2

test:
  commands:
    - python -c "import os; os.add_dll_directory(os.environ['SP_DIR'] + '\\clidriver\\bin'); import ibm_db; import ibm_db_dbi"  # [win]
  imports:
    - ibm_db  # [not win]
    - ibm_db_dbi  # [not win]

about:
  home: https://pypi.org/project/ibm-db/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Database API Specification v2.0
    The extension supports DB2 (LUW, zOS, i5) and IDS (Informix Dynamic Server)
  doc_url: https://github.com/ibmdb/python-ibmdb/wiki
  dev_url: https://github.com/ibmdb/python-ibmdb

extra:
  recipe-maintainers:
    - SabaKauser
    - xhochy
    - amukherjee28
